apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: lvfx17xd9-python
  janus-idp.io/tekton: lvfx17xd9-python
  backstage.io/kubernetes-id: lvfx17xd9-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: lvfx17xd9-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
